version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
      - run: npm run build

workflows:
  version: 2
  run_test:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
